### ISSUE TITLE
Full dataset application

### ISSUE THREAD

**Issue by ChenhaoLi89** [YuliWanghust/BrainMD#1]
Hello, I am a MS/PHD student majoring in ECE at UIUC. My research direction is VLM. I found that your dataset is very helpful for our research. How can I apply for the full dataset? I look forward to your reply.

**Comment by YuliWanghust** [comment]
Hi, this dataset-related paper is currently under review for a conference, and we should receive the results soon. Once it is accepted, I will follow up with you regarding the data usage agreement and how your lab can access the data.
